X=int (input("Enter the first number:"))
Y=int (input("Enter the second number"))
print("The Addition is",X+Y)
print("The Subtraction is",X-Y)
print("The Multiplication is",X*Y)
print("The Division is",X/Y)
print("The Exponential is",X**Y)
print("The Floor Division is",X//Y)
print("The Modulus is",X%Y)
